name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Firebase CLI
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > firebase-service-account.json
          firebase use --add

      - name: Deploy to Firebase
        run: |
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_AUTH_TOKEN }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json
